name: flutter_gotrip
description: GoTrip - Flutter client
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  provider: ^6.0.5
  flutter_dotenv: ^5.0.2
  geolocator: ^10.1.0
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  socket_io_client: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assests/env/
